# Generated by Django 4.1.5 on 2023-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
