# Generated by Django 4.1.5 on 2023-03-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_id',
        ),
    ]
