# Generated by Django 4.1.3 on 2022-11-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_comment",
            name="postId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Blog.post"
            ),
        ),
    ]
