# Generated by Django 4.1.3 on 2022-12-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_rename_image_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, unique=True)),
                ("project_description", models.CharField(max_length=200)),
                ("project_file", models.FileField(upload_to="projects/")),
                ("authors", models.CharField(max_length=200)),
            ],
        ),
    ]
