# Generated by Django 4.1.5 on 2023-02-21 11:17

import Exporter.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=Exporter.constants.generate_order_number, max_length=30, unique=True)),
                ('type_name', models.CharField(default=False, max_length=100)),
                ('warehouse', models.CharField(default=False, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('order_type', models.CharField(choices=[('Export', 'Export'), ('Import', 'Import')], max_length=20)),
                ('pickup_date', models.DateField(null=True)),
                ('pickup_status', models.CharField(default='PENDING', max_length=20, null=True)),
                ('delivery_status', models.CharField(default='pending', max_length=20, null=True)),
                ('contact_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('order_total', models.PositiveIntegerField(blank=True, default=500)),
                ('cname', models.CharField(default=False, max_length=50)),
                ('cemail', models.EmailField(default=False, max_length=50)),
                ('cphone', models.CharField(default=False, max_length=50)),
                ('caddress', models.TextField(default=False)),
                ('city', models.CharField(default=False, max_length=20)),
                ('state', models.CharField(default=False, max_length=20)),
                ('country', models.CharField(default=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='pending', max_length=20, null=True)),
                ('reserved_until', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Bambusa guvi', 'Bambusa guvi'), ('Bambusa bambua', 'Bambusa bambua'), ('Bambusa burmanica', 'Bambusa burmanica'), ('Bambusa vulgaris', 'Bambusa vulgaris'), ('Bambusa tulda', 'Bambusa tulda')], default=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=50)),
                ('address', models.TextField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField(default=50)),
                ('stock_capacity', models.IntegerField(default=500)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exporter.type')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exporter.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(default=Exporter.constants.generate_request_number, max_length=30, unique=True)),
                ('type_name', models.CharField(default=False, max_length=100)),
                ('warehouse', models.CharField(default=False, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('Export', 'Export'), ('Import', 'Import')], max_length=20)),
                ('pickup_date', models.DateField(null=True)),
                ('pickup_status', models.CharField(default='pending', max_length=20, null=True)),
                ('is_verfied', models.CharField(default='pending', max_length=20)),
                ('delivery_status', models.CharField(default='pending', max_length=20, null=True)),
                ('cname', models.CharField(default=False, max_length=50)),
                ('cemail', models.EmailField(default=False, max_length=50)),
                ('cphone', models.CharField(default=False, max_length=50)),
                ('caddress', models.TextField(default=False)),
                ('city', models.CharField(default=False, max_length=20)),
                ('state', models.CharField(default=False, max_length=20)),
                ('country', models.CharField(default=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_link', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exporter.order')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Exporter.request'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
